//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polesportivo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolesportivoEntities : DbContext
    {
        public PolesportivoEntities()
            : base("name=PolesportivoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Atleta> Atletas { get; set; }
        public DbSet<Modalidade> Modalidades { get; set; }
        public DbSet<Evento> Eventoes { get; set; }
        public DbSet<EventoModalidade> EventoModalidades { get; set; }
        public DbSet<Dados> Dados { get; set; }
    }
}
