//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polesportivo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dados
    {
        public int Id { get; set; }
        public int IdEvento { get; set; }
        public int IdAtleta { get; set; }
        public System.TimeSpan Largada { get; set; }
        public System.TimeSpan ChipLargada { get; set; }
        public System.TimeSpan Split1 { get; set; }
        public System.TimeSpan Split2 { get; set; }
        public System.TimeSpan Split3 { get; set; }
        public System.TimeSpan Split4 { get; set; }
        public System.TimeSpan Split5 { get; set; }
        public System.TimeSpan Split6 { get; set; }
        public System.TimeSpan Split7 { get; set; }
        public System.TimeSpan Split8 { get; set; }
        public System.TimeSpan Split9 { get; set; }
        public System.TimeSpan Split10 { get; set; }
        public System.TimeSpan Adjustment { get; set; }
        public System.TimeSpan Chegada { get; set; }
        public System.TimeSpan Total { get; set; }
    }
}
