//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polesportivo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventoModalidade
    {
        public int Id { get; set; }
        public int IdEvento { get; set; }
        public string Tipo { get; set; }
        public string Descricao { get; set; }
        public int Campo1 { get; set; }
        public int Campo2 { get; set; }
    }
}
